version: '3.7'

services:
  grafana:
    user: root
    image: grafana/grafana:latest
    ports:
      - '3090:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/redshift-datasource
      - /home/erik:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - /home/erik/code/grafana/grafana/conf/custom.ini:/etc/grafana/grafana.ini
    environment:
      - COMPOSE_INTERACTIVE_NO_CLI=1
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-redshift-datasource
volumes:
  grafana-storage:
